[package]
name = "mtg_lounge_collections"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.1"
bson = { version = "2", features = ["chrono-0_4"] }
chrono = "0.4"
mongodb = "2.1"
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.35.1", features = ["full"] }
