services:
    scryfall-cache:
        build: ./../scryfall-cache
        restart: always
        networks:
            - mtg-lounge

    pg-database:
        image: postgres
        restart: always
        volumes:
            - ./../container_data/db-data:/var/lib/postgresql/data/
        networks:
            - mtg-lounge
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=mtg_lounge

    mongo-database:
        image: mongo
        restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=password
        networks:
            - mtg-lounge

    rs-server:
        image: rust:1.84
        depends_on:
            - scryfall-cache
            - pg-database
            - mongo-database
        networks:
            - mtg-lounge
        volumes:
            - ./../backend:/usr/src
        command: >
            sh -c "
                cd /usr/src
                cargo install --path .
                cargo build --locked --release
                cp target/release/mtg_lounge_collections /bin/server
                /bin/server
            "

    elm-frontend:
        build: ./../frontend
        restart: always
        depends_on:
            - scryfall-cache
            - pg-database
            - mongo-database
        networks:
            - mtg-lounge
        volumes:
            - ./../frontend:/usr/src

networks:
    mtg-lounge:
        driver: bridge
